-- 자동 생성: DB/gen_table_doc.py --emit-comments
-- COMMENT 가 비어 있는 컬럼에 정의서의 설명을 넣습니다.
-- 실행해도 데이터는 바뀌지 않습니다 (메타데이터만).

-- 정정: 경락가 단일 타겟 시절 코멘트가 남아 있던 컬럼
COMMENT ON COLUMN crop_price_train.whsl_prc_lag3 IS '3영업일 전 중도매인 판매가(원/kg)';
COMMENT ON COLUMN crop_price_train.whsl_prc_lag7 IS '7영업일 전 중도매인 판매가(원/kg)';
COMMENT ON COLUMN crop_price_train.whsl_prc_avg7 IS '최근 7영업일 평균 중도매인 판매가(원/kg)';
COMMENT ON COLUMN crop_price_train.whsl_prc_avg14 IS '최근 14영업일 평균 중도매인 판매가(원/kg)';
COMMENT ON COLUMN crop_price_train.whsl_prc_std7 IS '최근 7영업일 중도매인 판매가 표준편차. 단기 가격 변동성';

COMMENT ON COLUMN veg_daily_price_raw.id IS 'DB 내부 식별자';
COMMENT ON COLUMN veg_daily_price_raw.exmn_ymd IS '조사일자';
COMMENT ON COLUMN veg_daily_price_raw.ctgry_cd IS '부류코드 (200=채소류)';
COMMENT ON COLUMN veg_daily_price_raw.ctgry_nm IS '부류명';
COMMENT ON COLUMN veg_daily_price_raw.item_cd IS '품목코드. 211 배추 · 231 무 · 241 고추 · 244 피마늘 · 245 양파 · 258 깐마늘. **품목은 이 컬럼으로 센다** (item_nm 은 원천이 바꾼다)';
COMMENT ON COLUMN veg_daily_price_raw.item_nm IS '품목명. **원천이 바꾼다** — 2026 부터 고추→건고추 · 마늘→피마늘. 필터·집계에 쓰지 말 것';
COMMENT ON COLUMN veg_daily_price_raw.vrty_cd IS '품종코드. 배추는 작형에 따라 교대';
COMMENT ON COLUMN veg_daily_price_raw.vrty_nm IS '품종명';
COMMENT ON COLUMN veg_daily_price_raw.grd_cd IS '등급코드 (04=상품, 05=중품)';
COMMENT ON COLUMN veg_daily_price_raw.grd_nm IS '등급명';
COMMENT ON COLUMN veg_daily_price_raw.se_cd IS '조사구분코드 (01 소매 · 02 중도매). 02 는 경락가가 아님';
COMMENT ON COLUMN veg_daily_price_raw.se_nm IS '조사구분명';
COMMENT ON COLUMN veg_daily_price_raw.sgg_cd IS '시군구코드 (1101=서울). 소매 필터에 사용';
COMMENT ON COLUMN veg_daily_price_raw.sgg_nm IS '시군구명';
COMMENT ON COLUMN veg_daily_price_raw.mrkt_cd IS '시장코드';
COMMENT ON COLUMN veg_daily_price_raw.mrkt_nm IS '시장명 (중도매 필터: 가락도매)';
COMMENT ON COLUMN veg_daily_price_raw.unit IS '단위 문자열. kg/포기/g 혼재';
COMMENT ON COLUMN veg_daily_price_raw.unit_sz IS '단위크기. 원/kg 정규화의 분모';
COMMENT ON COLUMN veg_daily_price_raw.exmn_dd_prc IS '조사일 가격 (unit/unit_sz 기준)';
COMMENT ON COLUMN veg_daily_price_raw.exmn_dd_cnvs_prc IS '조사일 kg 환산가격 (원천 제공값)';
COMMENT ON COLUMN veg_daily_price_raw.orgnl_reg_dt IS '원본 등록일시';
COMMENT ON COLUMN veg_daily_price_raw.created_at IS 'DB 적재 시각';
COMMENT ON COLUMN auction_prices_daily.id IS 'DB 내부 식별자';
COMMENT ON COLUMN auction_prices_daily.auction_date IS '경매일자';
COMMENT ON COLUMN auction_prices_daily.market_category IS '시장 부류';
COMMENT ON COLUMN auction_prices_daily.wholesale_market_code IS '도매시장 코드 (110001=서울가락)';
COMMENT ON COLUMN auction_prices_daily.wholesale_market_name IS '도매시장명';
COMMENT ON COLUMN auction_prices_daily.item_code IS '품목코드';
COMMENT ON COLUMN auction_prices_daily.item_name IS '품목명';
COMMENT ON COLUMN auction_prices_daily.grade_name IS '등급명 (11=특)';
COMMENT ON COLUMN auction_prices_daily.avg_auction_price_krw_per_kg IS '평균 경락가(원/kg). auc_prc_lag1 의 원천';
COMMENT ON COLUMN auction_prices_daily.min_auction_price_krw_per_kg IS '최저 경락가(원/kg). 일중 스프레드 계산에 사용';
COMMENT ON COLUMN auction_prices_daily.max_auction_price_krw_per_kg IS '최고 경락가(원/kg). 일중 스프레드 계산에 사용';
COMMENT ON COLUMN auction_prices_daily.trade_volume_kg IS '거래물량(kg). auc_vol_lag1 의 원천';
COMMENT ON COLUMN auction_prices_daily.trade_amount_krw IS '거래금액(원)';
COMMENT ON COLUMN auction_prices_daily.package_trade_quantity IS '포장 거래수량';
COMMENT ON COLUMN auction_prices_daily.source_trade_count IS '집계에 사용된 원천 거래 건수';
COMMENT ON COLUMN auction_prices_daily.source IS '출처 API 표기';
COMMENT ON COLUMN daily_volume.base_date IS '기준일자. PK(1)';
COMMENT ON COLUMN daily_volume.item_label IS '품목명. PK(2)';
COMMENT ON COLUMN daily_volume.total_ton IS '일 합계 반입량(톤)';
COMMENT ON COLUMN daily_volume.top1_region IS '1위 산지. 반입 0톤인 날은 NULL';
COMMENT ON COLUMN daily_volume.top1_ton IS '1위 산지 물량(톤)';
COMMENT ON COLUMN daily_volume.top2_region IS '2위 산지';
COMMENT ON COLUMN daily_volume.top2_ton IS '2위 산지 물량(톤)';
COMMENT ON COLUMN daily_volume.etc_ton IS '1·2위 외 기타 산지 합계(톤)';
COMMENT ON COLUMN daily_volume.req_date IS '수집 일자. base_date 보다 0~7일 늦다. as-of 결합의 기준';
COMMENT ON COLUMN daily_volume.top1_raw IS '1위 원문. 구분자가 NBSP(U+00A0)';
COMMENT ON COLUMN daily_volume.top2_raw IS '2위 원문';
COMMENT ON COLUMN daily_volume.loaded_at IS 'DB 적재 시각';
COMMENT ON COLUMN daily_volume_stg.ymd IS '스테이징(text). 현재 미사용';
COMMENT ON COLUMN daily_volume_stg.item_label IS '스테이징(text). 현재 미사용';
COMMENT ON COLUMN daily_volume_stg.total_ton IS '스테이징(text). 현재 미사용';
COMMENT ON COLUMN daily_volume_stg.top1_raw IS '스테이징(text). 현재 미사용';
COMMENT ON COLUMN daily_volume_stg.top1_ton IS '스테이징(text). 현재 미사용';
COMMENT ON COLUMN daily_volume_stg.top2_raw IS '스테이징(text). 현재 미사용';
COMMENT ON COLUMN daily_volume_stg.top2_ton IS '스테이징(text). 현재 미사용';
COMMENT ON COLUMN daily_volume_stg.etc_ton IS '스테이징(text). 현재 미사용';
COMMENT ON COLUMN daily_volume_stg.mmdd IS '스테이징(text). 현재 미사용';
COMMENT ON COLUMN daily_volume_stg.req_date IS '스테이징(text). 현재 미사용';
COMMENT ON COLUMN ref_holiday.dt IS '날짜. PK(1)';
COMMENT ON COLUMN ref_holiday.date_name IS '공휴일명. PK(2)';
COMMENT ON COLUMN ref_holiday.date_kind IS '특일 종류 코드';
COMMENT ON COLUMN ref_holiday.is_holiday IS '공휴일 여부';
COMMENT ON COLUMN ref_holiday.seq IS '같은 날 순번';
COMMENT ON COLUMN ref_calendar_override.dt IS '날짜. PK(1)';
COMMENT ON COLUMN ref_calendar_override.axis IS 'open(경매) 또는 survey(조사). PK(2)';
COMMENT ON COLUMN ref_calendar_override.is_on IS '그 축에서 여는가';
COMMENT ON COLUMN ref_calendar_override.note IS '사유. ''미검증'' 은 공고 기준이라 실거래 대조 전';
